apiVersion: v1
kind: Secret
metadata:
  name: sql
type: Opaque
data:
  SQL_USER: sqladminxSf4718
  SQL_PASSWORD: aO2du2Bl2
  SQL_SERVER: sqlserverxsf4718.database.windows.net
  SQL_DBNAME: mydrivingDB
  
